### ISSUE TITLE
WF_out size definition in WF_shift_kpoint

### ISSUE THREAD

**Issue by andrea-ferretti** [yambo-code/yambo#192]
Dear all,

just looking around the code, in src/wf_and_fft/WF_shift_kpoint.F I noticed the following loop:

     do ig=1,wf_ng
       if(ig>ng_max) cycle
       igp=G_m_G(ig,g0_idx(id,WF_shift(id)))
       if(igp>wf_ng.or.ig>wf_ng) cycle
       WF_k_out(igp,:,:,:)=WF_tmp(ig,:,:,:)
     enddo

while the loo could be prob rewritten and
`do ig = 1, min(ng_max,wf_ng)`, I do not understand the condition
      ` if(igp>wf_ng.or.ig>wf_ng) cycle`
where .or.ig>wf_ng  seems redundant to me.
Is this wanted ?
I suspect something else was actually meant.
What about 
  `if(igp>wf_ng.or.ig>wf_ng) cycle`
(just a blind guess)

A

**Comment by sangallidavide** [comment]
I add here a discussion on the way shifts are accounted for in the subroutine 
https://github.com/yambo-code/yambo/blob/master/src/dipoles/DIPOLE_overlaps.F

Yambo has kpts with  `-0.5<k(idir,ikbz) < 0.5`
The subroutine wants kpts with  `0.<k(idir,ikbz_shifted) < 1` accordingly it records the shift, WF_shift(ikbz,:)
```
     if(Xk%ptbz(ik,id)<-EPS) then                                       
        WF_shifts(ik,id)=1                                              
     elseif(Xk%ptbz(ik,id)>1._SP-EPS) then                              
        WF_shifts(ik,id)=2                                              
     endif
```
which is later applied via
https://github.com/yambo-code/yambo/blob/master/src/wf_and_fft/WF_shift_kpoint.F

This is done with these lines inside DIPOLE_overlaps.F
```
       call WF_symm_kpoint_gpu((/ib,ib/),ikbz,i_sp_pol,Xk,WF_symm)
       WF_tmp=>WF_ik(:,:,ib:ib)
       call WF_shift_kpoint_gpu((/ib,ib/),1,ikbz,i_sp_pol,WF_shifts(ikbz,:),Xk,WF_symm,WF_tmp)
```
After these operations, the wf at ikbz_shifted in the range (0,1) is loaded

Later the subroutine also needs the wf at ikbz_shifted+iq to evaluate the overlap matrix
Given `0.<k(idir,ikbz_shifted) < 1` we have  `0+iq<k(idir,ikbz_shifted+iq) < 1+iq`

The code will find ikpbz_shifted, e.g. between 0 and 1 corresponding to ikbz_shifted+iq up to a shift, let's call it q_shift(:)
Now we have a first shift needed to get ikpbz_shifted from ikpbz. This is stored inside WF_shift(ikbz,:).
Plus we have the second shift, q_shift.

What  I do not understand is how the final shift, e.g. WF_shift(ikbz,:)+q_shift is obtained via the following lines
```
         shift=WF_shifts(ikbzp,:)
         if(USE_shifted_wf) then
           if(WF_shifts(ikbzp,id)==1) shift(id)=1
           if(WF_shifts(ikbzp,id)==0) shift(id)=1
           if(WF_shifts(ikbzp,id)==2) shift(id)=0
         endif
```

In general, if I have a first positive shift (WF_shifts(ikbzp,:)=1 for some direction) and possibly a second positive shift in the same direction due to the +q shift, couldn't this become a larger shift in such direction (?). Maybe it never happens because iq is always small.

Side note. The following code would be easier to read 
```
     if(Xk%ptbz(ik,id)<-EPS) then                                       
        WF_shifts(ik,id)=+1                                              
     elseif(Xk%ptbz(ik,id)>1._SP-EPS) then                              
        WF_shifts(ik,id)=-1                                              
     endif
```
and later
```
         shift=WF_shifts(ikbzp,:)
         if(USE_shifted_wf) then
           if(WF_shifts(ikbzp,id)==+1) shift(id)=+1
           if(WF_shifts(ikbzp,id)== 0) shift(id)=+1
           if(WF_shifts(ikbzp,id)==-1) shift(id)=0
         endif
```
